name: CI
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.12]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Clone repo
        uses: actions/checkout@v2

      - name: Install python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup poetry package manager
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Check codestyle
        if: matrix.os == 'ubuntu-latest'
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "jaft tests"
          use-pylint: false
          use-pycodestyle: true
          use-flake8: false
          use-black: false
          use-mypy: false
          use-isort: false
      
      - name: Install dependencies
        run: |
          poetry install
      
      - name: Generate fake SSH keys for tests (For Bash)
        if: matrix.os == 'ubuntu-latest'
        run: ssh-keygen -f ./id_rsa -q -N ''
      
      - name: Generate fake SSH keys for tests(For Powershell)
        if: matrix.os == 'windows-latest'
        run: ssh-keygen -f ./id_rsa -q -N '""'

      - name: Run tests
        run: poetry run pytest -v tests/

